apiVersion: v1
kind: Service
metadata:
  name: {{ include "trex-exporter.fullname" . }}
  labels:
    {{- include "trex-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 9102
      targetPort: 9102
      protocol: TCP
      name: metrics
  selector:
    {{- include "trex-exporter.selectorLabels" . | nindent 4 }}
