name: Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      env:
        TARGETARCH: amd64
      run: |
        docker build .  --tag ghcr.io/$GITHUB_REPOSITORY:${{github.ref_name}} --tag ghcr.io/$GITHUB_REPOSITORY:latest
        docker push -a ghcr.io/$GITHUB_REPOSITORY
